#!/bin/sh
# File by: Truneosprinter | 2024

# ╔==================================╗
# ║         _       _ _              ║
# ║   __  _(_)_ __ (_) |_ _ __ ___   ║
# ║   \ \/ / | '_ \| | __| '__/ __|  ║
# ║    >  <| | | | | | |_| | | (__   ║
# ║   /_/\_\_|_| |_|_|\__|_|  \___|  ║
# ║                                  ║
# ╚==================================╝

# run Picom (eyecandy compositor)
picom --config ~/.config/picom/picom.conf &

# run Feh for wallpaper
feh --bg-fill ~/Pictures/monokai_wallpaper.png &

# set British keyboard map
setxkbmap gb &

# execute window manager (dwm)
exec dwm

